sudo: false
language: node_js
node_js:
- iojs
- '0.12'
- '0.10'
deploy:
  provider: npm
  email: chris@enlightenmint.com
  api_key:
    secure: DloaAX1KfMjROIzrmsm3GzY9YLwBv2PWIlut1UCKmdcjKM5VXAyyWdpZH/lTwxPu2DZwj82L1jiv+WFd/UHwo/3JCDsni2YrcfNBTlxjkRGR3SlW59YiH4BwgUoQFKcniIX2GyLZjNrPiy8LbUQ+tKt+XBP+ieuBz0q5Dr12Q5g=
  on:
    tags: true
