sudo: false
language: node_js
node_js:
- iojs
- '0.12'
- '0.10'
deploy:
  provider: npm
  email: chris@enlightenmint.com
  api_key:
    secure: s+zxZwXUL2rUuXQMkgnnceOQvJ6fMqny9yttDG6v/wKv+aABZAOmm0Co5QX1d1Ly1hQw1h7erIDHoT+oxToom34D0EazUzGT6w5vZuTaDVVZ3CShGIZd+X1D3VsaV9M6An7JNCARaSjfaA7f3v9uwyytC3vVfsPN/Vk0rgKVETo=
  on:
    tags: true
